version: '3.10'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=zMSmyKrbOwBSQ7p1B5c9fJh9d5zmawR
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DEBUG=1
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data:
