# Generated by Django 4.0 on 2022-03-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medcine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('international_name', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('sources', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('documentation', models.URLField()),
                ('medcine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_page.medcine')),
            ],
        ),
    ]
