# Generated by Django 4.0 on 2022-05-25 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medcine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('international_name', models.CharField(max_length=300, unique=True, verbose_name='МНН')),
                ('general_url_name', models.CharField(max_length=50, unique=True, verbose_name='Название для URL')),
                ('general_info', models.TextField(blank=True, verbose_name='Информация')),
                ('formula', models.ImageField(blank=True, upload_to='formulas/%Y/%m/%d', verbose_name='Химическая формула')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('pub_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('general_documentation', models.URLField(blank=True, verbose_name='Ссылка на документацию')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
                'ordering': ['international_name'],
            },
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_name', models.CharField(max_length=50, unique=True, verbose_name='Торговое наименование')),
                ('url_name', models.CharField(max_length=50, verbose_name='Название для URL')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата публикации')),
                ('pub_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('medcine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_page.medcine', verbose_name='Международное наименование')),
            ],
            options={
                'verbose_name': 'Синоним',
                'verbose_name_plural': 'Синонимы',
                'ordering': ['comm_name'],
            },
        ),
        migrations.CreateModel(
            name='Request_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Число запросов')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата запроса')),
                ('synonym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_page.synonyms', verbose_name='Синоним')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='General_sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=500, verbose_name='Название источника')),
                ('medcine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_page.medcine', verbose_name='МНН')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['source_name'],
            },
        ),
    ]
