# Generated by Django 4.0 on 2022-05-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_sources',
            name='source_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='medcine',
            name='formula',
            field=models.ImageField(blank=True, null=True, upload_to='formulas/%Y/%m/%d', verbose_name='Химическая формула'),
        ),
        migrations.AlterField(
            model_name='medcine',
            name='general_documentation',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на документацию'),
        ),
    ]
