# Generated by Django 4.0 on 2022-03-31 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medcine',
            options={'ordering': ['international_name'], 'verbose_name': 'Препарат', 'verbose_name_plural': 'Препараты'},
        ),
        migrations.AlterModelOptions(
            name='synonyms',
            options={'ordering': ['comm_name'], 'verbose_name': 'Синоним', 'verbose_name_plural': 'Синонимы'},
        ),
        migrations.RemoveField(
            model_name='medcine',
            name='info',
        ),
        migrations.RemoveField(
            model_name='medcine',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='synonyms',
            name='name',
        ),
        migrations.AddField(
            model_name='medcine',
            name='general_documentation',
            field=models.URLField(null=True, verbose_name='Ссылка на документацию'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='general_info',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='general_sources',
            field=models.TextField(null=True, verbose_name='Литература'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synonyms',
            name='comm_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Торговое наименование'),
        ),
        migrations.AddField(
            model_name='synonyms',
            name='info',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='synonyms',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synonyms',
            name='sources',
            field=models.TextField(null=True, verbose_name='Литература'),
        ),
        migrations.AlterField(
            model_name='medcine',
            name='international_name',
            field=models.CharField(max_length=50, verbose_name='МНН'),
        ),
        migrations.AlterField(
            model_name='synonyms',
            name='documentation',
            field=models.URLField(null=True, verbose_name='Ссылка на документацию'),
        ),
        migrations.AlterField(
            model_name='synonyms',
            name='medcine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='start_page.medcine'),
        ),
    ]
