# Generated by Django 4.0 on 2022-04-09 12:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medcine',
            options={'ordering': ['international_name'], 'verbose_name': 'Препарат', 'verbose_name_plural': 'Препараты'},
        ),
        migrations.AlterModelOptions(
            name='synonyms',
            options={'ordering': ['comm_name'], 'verbose_name': 'Синоним', 'verbose_name_plural': 'Синонимы'},
        ),
        migrations.RemoveField(
            model_name='medcine',
            name='info',
        ),
        migrations.RemoveField(
            model_name='medcine',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='synonyms',
            name='documentation',
        ),
        migrations.RemoveField(
            model_name='synonyms',
            name='name',
        ),
        migrations.AddField(
            model_name='medcine',
            name='general_documentation',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на документацию'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='general_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='general_url_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название для URL'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='synonyms',
            name='comm_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Торговое наименование'),
        ),
        migrations.AddField(
            model_name='synonyms',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='synonyms',
            name='url_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название для URL'),
        ),
        migrations.AlterField(
            model_name='medcine',
            name='international_name',
            field=models.CharField(max_length=300, verbose_name='МНН'),
        ),
        migrations.AlterField(
            model_name='synonyms',
            name='medcine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='start_page.medcine', verbose_name='Международное наименование'),
        ),
        migrations.CreateModel(
            name='Request_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Число запросов')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запроса')),
                ('synonym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start_page.synonyms', verbose_name='Синоним')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='General_sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название источника')),
                ('medcine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start_page.medcine', verbose_name='МНН')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['source_name'],
            },
        ),
    ]
