# Generated by Django 4.0 on 2022-05-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0002_alter_general_sources_source_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_sources',
            name='source_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='medcine',
            name='formula',
            field=models.ImageField(blank=True, upload_to='formulas/%Y/%m/%d', verbose_name='Химическая формула'),
        ),
        migrations.AlterField(
            model_name='medcine',
            name='general_documentation',
            field=models.URLField(blank=True, verbose_name='Ссылка на документацию'),
        ),
        migrations.AlterField(
            model_name='synonyms',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
    ]
