# Generated by Django 4.0 on 2022-04-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0003_alter_request_counter_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request_counter',
            options={'ordering': ['-date'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
    ]
