# Generated by Django 4.0 on 2022-05-02 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0004_alter_request_counter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcine',
            name='international_name',
            field=models.CharField(error_messages={'invalid': 'Введите название латиницей'}, max_length=300, validators=[django.core.validators.RegexValidator(message='Ввод латиницей', regex='^[a-z][0-9]$')], verbose_name='МНН'),
        ),
    ]
