# Generated by Django 4.0 on 2022-04-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0004_remove_synonyms_documentation_remove_synonyms_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название источника')),
                ('medcine', models.ManyToManyField(to='start_page.Medcine', verbose_name='МНН')),
            ],
        ),
    ]
