# Generated by Django 4.0 on 2022-05-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0005_alter_medcine_international_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcine',
            name='international_name',
            field=models.CharField(max_length=300, verbose_name='МНН'),
        ),
    ]
