# Generated by Django 4.0 on 2022-04-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0006_alter_sources_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название источника')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['source_name'],
            },
        ),
        migrations.RemoveField(
            model_name='medcine',
            name='general_sources',
        ),
        migrations.DeleteModel(
            name='Sources',
        ),
        migrations.AddField(
            model_name='medcine',
            name='general_sources',
            field=models.ManyToManyField(to='start_page.General_sources', verbose_name='Источники'),
        ),
    ]
