# Generated by Django 4.0 on 2022-05-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0006_alter_medcine_international_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcine',
            name='international_name',
            field=models.CharField(max_length=300, unique=True, verbose_name='МНН'),
        ),
        migrations.AlterField(
            model_name='synonyms',
            name='medcine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_page.medcine', verbose_name='Международное наименование'),
        ),
    ]
