# Generated by Django 4.0 on 2022-05-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0007_alter_medcine_international_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonyms',
            name='medcine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start_page.medcine', verbose_name='Международное наименование'),
        ),
    ]
