# Generated by Django 4.0 on 2022-05-14 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0009_alter_synonyms_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonyms',
            name='pub_date',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2022, 5, 14, 15, 58, 24, 499216, tzinfo=utc), null=True, verbose_name='Дата публикации'),
        ),
    ]
