# Generated by Django 4.0 on 2022-05-15 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0010_alter_synonyms_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonyms',
            name='pub_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации'),
        ),
    ]
