# Generated by Django 4.0 on 2022-05-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0011_alter_synonyms_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medcine',
            name='formula',
            field=models.ImageField(blank=True, upload_to='formulas/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='medcine',
            name='pub_update',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='synonyms',
            name='pub_update',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='general_sources',
            name='source_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='synonyms',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
