# Generated by Django 4.0 on 2022-05-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0012_medcine_formula_medcine_pub_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcine',
            name='formula',
            field=models.ImageField(blank=True, upload_to='formulas/%Y/%m/%d', verbose_name='Химическая формула'),
        ),
    ]
