# Generated by Django 4.0 on 2022-05-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0014_alter_general_sources_medcine_alter_synonyms_medcine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_counter',
            name='synonym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_page.synonyms', verbose_name='Синоним'),
        ),
    ]
